export class BusinessOperationInfoModel {
  constructor(
    public id: string,
    public business_activity: string,
    public business_area: number,
    public total_floor_area: number,
    public number_male_employee: number,
    public number_female_employee: number,
    public total_number_employee_establishment: number,
    public total_number_employee_residing_lgu: number,
    public has_delivery_vehicles: boolean,
    public total_delivery_vehicle_van_truck: number,
    public total_delivery_vehicle_motorcycle: number,
    public place_owned_rented: string,
    public taxdec_number: string,
    public property_index_number: string,
    public government_tax_incentives_enjoy: string,
    public community_tax_certificate: string,
    public barangay_micro_business_enterprise_registered: string,
    public bangko_sentral_registered: string,
    public remarks: string,
  ) {
    return {
      id,
      business_activity,
      business_area,
      total_floor_area,
      number_male_employee,
      number_female_employee,
      total_number_employee_establishment,
      total_number_employee_residing_lgu,
      has_delivery_vehicles,
      total_delivery_vehicle_van_truck,
      total_delivery_vehicle_motorcycle,
      place_owned_rented,
      taxdec_number,
      property_index_number,
      government_tax_incentives_enjoy,
      community_tax_certificate,
      barangay_micro_business_enterprise_registered,
      bangko_sentral_registered,
      remarks,
    }
  }
}